### 📎 목차

1. [비동기 처리를 위한 콜백 패턴의 단점](#1-비동기-처리를-위한-콜백-패턴의-단점)
2. [프로미스의 생성](#2-프로미스의-생성)
3. [프로미스의 후속 처리 메서드](#3-프로미스의-후속-처리-메서드)
4. [프로미스의 에러 처리](#4-프로미스의-에러-처리)
5. [프로미스 체이닝](#5-프로미스-체이닝)
6. [프로미스의 정적 메서드](#6-프로미스의-정적-메서드)
7. [마이크로태스크 큐(microtask queue/job queue)](#7-마이크로태스크-큐microtask-queuejob-queue)
8. [fetch](#8-fetch)

---

# 45장. 프로미스

## 1) 비동기 처리를 위한 콜백 패턴의 단점

### (1) 콜백 헬

- **비동기 함수**

  - 함수 내부에 비동기로 동작하는 코드를 포함한 함수
  - 비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료됨 ⇒ **비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료**
  - 따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당할 경우 기대한 대로 동작하지 않음

  ⇒ 비동기 함수의 처리 결과(서버의 응답 등)에 대한 후속 처리는 비동기 함수 내부에서 수행해야 하며 이를 위해 콜백 함수를 전달하는 것이 일반적이다.

  ⇒ 필요에 따라 비동기 처리가 성공하면 호출될 콜백 함수와 실패하면 호출될 콜백 함수를 전달

- **콜백 헬**
  - 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상
  - 콜백 헬은 코드의 depth가 깊어지므로 가독성도 떨어지며 실수를 유발하는 원인이 된다.
  ```jsx
  // 콜백 지옥 ⇒ 콜백 함수의 중첩
  get(`step1`, (a) => {
    get(`step2/${a}`, (b) => {
      get(`step3/${b}`, (c) => {
        console.log(c);
      });
    });
  });
  ```

<br/>

### (2) 에러 처리의 한계

- 비동기 처리를 위한 콜백 패턴의 가장 큰 문제점 ⇒ 에러처리가 곤란하다는 점

```jsx
try {
  // 1초 후 콜백 함수가 실행되도록 타이머 설정
  setTimeout(() => {
    throw new Error("Error!");
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못함
  console.error("캐치한 에러", e);
}
```

- **에러는 호출자(caller) 방향으로 전파**된다.
  - 콜스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다.
- 위의 예제에서 ,콜백 함수 내부에서 던진 에러가 `catch` 코드 블록에서 캐치되지 않음
  - Why?
    - 비동기 함수 `setTimeout`이 호출 → `setTimeout` 함수의 실행 컨텍스트 생성 → 콜스택에 `push`되어 실행 → `setTimeout` 함수 즉시 종료 → 콜스택에서 `pop` → 타이머가 만료되면 `setTimeout`의 콜백 함수는 태스크큐로 `push` → 콜스택이 비었을 경우, 이벤트 루프에 의해 콜백 함수의 실행 컨텍스트가 콜스택으로 `push` → 콜백 함수 실행 및 종료 → 콜스택에서 `pop`
    - 즉, `setTimeout` 함수의 콜백 함수가 실행되는 시점에는 이미 `setTimeout` 함수가 콜 스택에서 제거된 상태 ⇒ `setTimeout`의 콜백 함수를 호출한 것이 `setTimeout` 함수가 아니라는 것을 의미
    - 따라서, `setTimeout` 함수의 콜백 함수를 호출한 호출자는 `setTimeout` 함수가 아니므로, 콜백 함수가 발생시킨 에러는 `catch` 블록에서 캐치되지 않음
- 이러한 에러 처리의 한계를 극복하기 위해 **ES6에서 프로미스(Promise)가 도입**됨

<br/><br/>

## 2) 프로미스의 생성

- **프로미스(Promise)**
  - ES6에서 도입된 ECMAScript 사양에 정의된 표준 빌트인 객체 (호스트 객체 ❌)
  - `Promise` 생성자 함수를 `new` 연산자와 함께 호출하면 프로미스 객체를 생성한다.
  - **프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체**
- **`Promise` 생성자 함수**
  - 비동기 처리를 수행할 콜백 함수인 `excutor`를 인수로 전달 받는다.
  - `executor`함수에 전달되는 2가지 콜백함수 ⇒ `resolve`, `reject` 함수
    - **비동기 처리가 성공**하면 비동기 처리 결과를 **`resolve`함수**에 인수로 전달하면서 호출
    - **비동기 처리가 실패**하면 에러를 **`reject`함수**에 인수로 전달하면서 호출
- 비동기 처리의 상태 정보
  | 프로미스의 상태 정보 | 의미 | 상태 변경 조건 |
  | -------------------- | ------------------------------------- | -------------------------------- |
  | `pending` | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
  | `fulfilled` | 비동기 처리가 수행된 상태(성공) | `resolve` 함수 호출 |
  | `rejected` | 비동기 처리가 수행된 상태(실패) | `reject` 함수 호출 |

  - 생성된 직후의 프로미스는 기본적으로 `pending` 상태
  - 이후 비동기 처리가 수행되면 그 결과에 따라 프로미스의 상태가 변경된다.

    - 비동기 처리 성공 : `resolve` 함수를 호출하여 프로미스를 `fulfilled` 상태로 변경
    - 비동기 처리 실패 : `reject` 함수를 호출하여 프로미스를 `rejected` 상태로 변경
      ⇒ 프로미스의 상태는 `resolve` 또는 `reject` 함수를 호출하는 것으로 결정됨!

    ![1](https://github.com/hongii/book-shop-fe/assets/93701887/f144c25c-db9a-449f-9298-248a4e2eb368)

- `settled` 상태
  - `fulfilled` 또는 `rejected` 상태와 상관없이 `pending`이 아닌 상태로 비동기 처리가 수행된 상태
  - 프로미스는 `pending` 상태에서 `settled` 상태로 변할 수 있지만, 일단 `settled` 상태가 되면 더는 다른 상태로 변화할 수 없다.
- ex1) 비동기 처리가 성공한 경우

  - 프로미스는 `pending` 상태에서 `fulfilled` 상태로 변화
  - 비동기 처리 결과인 `1`을 값으로 가짐

  ![2](https://github.com/hongii/book-shop-fe/assets/93701887/6e4cf055-bbba-4ccf-b4b0-bff2ca088d07)

- ex2) 비동기 처리가 실패한 경우

  - 프로미스는 `pending` 상태에서 `rejected` 상태로 변화
  - 비동기 처리 결과인 `Error` 객체를 값으로 가짐

  ![3](https://github.com/hongii/book-shop-fe/assets/93701887/169b6b11-88e3-4ff5-9dd2-a732f7a3424e)

<br/><br/>

## 3) 프로미스의 후속 처리 메서드

- 프로미스의 비동기 처리 상태가 변화하면 이에 따른 후속 처리를 해야함 ⇒ 프로미스는 후속 메서드 `then`, `catch`, `finally`를 제공
- **프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.**
  - 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달
  - 모든 후속 처리 메서드는 프로미스를 반환하며, 비동기로 동작

<br/>

### **(1) `Promise.prototype.then`**

```jsx
// fulfilled
new Promise((resolve) => resolve("fulfilled")).then(
  (v) => console.log(v),
  (e) => console.error(e),
); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error("rejected"))).then(
  (v) => console.log(v),
  (e) => console.error(e),
); // Error: rejected
```

- `then` 메서드는 두 개의 콜백 함수를 인수로 전달받는다.
  - 첫 번째 콜백 함수
    - 비동기 처리가 성공했을 때 호출되는 성공 처리 콜백 함수
    - 프로미스가 `fulfilled` 상태(`resolve` 함수가 호출된 상태)가 되면 호출
    - 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.
  - 두 번째 콜백 함수
    - 비동기 처리가 실패했을 때 호출되는 실패 처리 콜백 함수
    - 프로미스가 `rejected` 상태(`reject` 함수가 호출된 상태)가 되면 호출
    - 이때 콜백 함수는 프로미스의 에러를 인수로 전달받는다.
- `then` 메서드는 언제나 프로미스를 반환한다.
  - `then` 메서드의 콜백 함수가 프로미스를 반환할 경우 ⇒ 해당 프로미스를 그대로 반환
  - `then` 메서드의 콜백 함수가 프로미스가 아닌 값을 반환할 경우 ⇒ 그 값을 암묵적으로 `resolve` 또는 `reject`하여 프로미스를 생성해 반환

<br/>

### **(2) `Promise.prototype.catch`**

```jsx
// rejected
new Promise((_, reject) => reject(new Error("rejected"))).catch((e) => console.error(e)); // Error: rejected
```

- `catch` 메서드는 한 개의 콜백 함수를 인수로 전달받는다.
- `catch` 메서드의 콜백 함수는 프로미스가 `rejected` 상태인 경우에만 호출된다.
- `catch` 메서드는 `then(undefined, onRejected)`과 동일하게 동작 ⇒ `then` 메서드와 마찬가지로 언제나 프로미스를 반환

<br/>

### (3) **`Promise.prototype.finally`**

```jsx
new Promise(() => {}).finally(() => console.log("finally")); // finally
```

- `finally` 메서드는 한 개의 콜백 함수를 인수로 전달받는다.
- `finally` 메서드의 콜백 함수는 프로미스의 성공 또는 실패와 상관없이 무조건 한 번 호출된다.
- 프로미스의 상태와 상관없이 공통적으로 수행해야할 처리 내용이 있을 때 유용함
- `then`/`catch`메서드와 마찬가지로 언제나 프로미스를 반환

<br/><br/>

## 4) 프로미스의 에러 처리

- 비동기 처리에서 발생한 에러 처리 방법 2가지

  1. `then` 메서드의 두 번째 콜백 함수에서 처리

     - 단, 이 경우에는 `then` 메서드의 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하고 코드가 복잡해지므로 가독성이 좋지 않음

     ```jsx
     const url = "https://jsonplaceholder.typicode.com/todos/1";
     promiseGet(url).then(
       (res) => console.xxx(res),
       (error) => console.log(error),
     ); // then 메서드의 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러는 캐치❌
     ```

  2. `catch` 메서드로 처리

     - `catch` 메서드를 호출하면 내부적으로 `then(undefined, onRejected)`을 호출
     - `catch` 메서드를 모든 `then` 메서드를 호출한 이후에 호출하면, 비동기 처리에서 발생한 에러(`rejected` 상태) 뿐만 아니라 `then` 메서드 내부에서 발생한 에러까지 모두 캐치 가능
     - 따라서, 에러 처리는 `catch` 메서드에서 하는 것을 권장

     ```jsx
     // ex1) 부적절한 url로 요청보낸 경우 => 에러 발생
     const wrongUrl = "https://jsonplaceholder.typicode.com/xxx/1";
     promiseGet(wrongUrl)
       .then((res) => console.log(res))
       .catch((error) => console.log(error));

     // ex2) 정상적인 url로 요청을 보냈으나 then 메서드의 첫 번째 콜백 함수에서 에러가 발생한 경우
     const url = "https://jsonplaceholder.typicode.com/todos/1";
     promiseGet(url)
       .then((res) => console.xxx(res)) // 에러 발생 => catch 블럭에서 캐치⭕
       .catch((error) => console.log(error)); // TypeError: console.xxx is not a function
     ```

<br/><br/>

## 5) 프로미스 체이닝

- **`then`, `catch`, `finally` 후속 처리 메서드는** 언제나 프로미스를 반환하므로 **연속적으로 호출 가능** ⇒ **프로미스 체이닝(Promise chaining)**
- 후속 처리 메서드는 콜백 함수가 반환한 프로미스를 반환한다.
  - 콜백 함수가 프로미스가 아닌 값을 반환하더라도 그 값을 암묵적으로 `resolve` 또는 `reject`하여 프로미스를 생성해 반환
- 프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리하므로 콜백 헬이 발생하지 않는다.
  - 하지만 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아니다.
  - 이러한 콜백 패턴을 해결해주기 위해 등장한 것이 ES8에서 도입된 **`async/await`**
- **`async/await`**
  - ES8에서 도입
  - 프로미스의 후속 처리 메서드 없이 마치 동기 처리처럼 프로미스가 처리 결과를 반환하도록 구현 가능
  - `async/await`도 프로미스를 기반으로 동작(46.6절 참고)

<br/><br/>

## 6) 프로미스의 정적 메서드

- `Promise`는 주로 생성자 함수로 사용되지만, 함수도 객체이므로 메서드를 가질 수 있다.
- `Promise`는 5가지 정적 메서드를 제공한다.

<br/>

### **(1) `Promise.resolve` / `Promise.reject`**

- 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용
- `Promise.resolve` 메서드

  - 인수로 전달받은 값을 `resolve`하는 프로미스를 생성

  ```jsx
  // 배열을 resolve하는 프로미스를 생성
  const resolvePromise = Promise.resolve([1, 2, 3]);
  resolvePromise.then(console.log); // [1, 2, 3]

  // 위의 코드와 동일하게 동작
  const resolvePromise = new Promise((resolve) => resolve([1, 2, 3]));
  resolvePromise.then(console.log); // [1, 2, 3]
  ```

- `Promise.reject` 메서드

  - 인수로 전달받은 값을 `reject`하는 프로미스를 생성

  ```jsx
  // 에러 객체를 reject하는 프로미스를 생성
  const rejectedPromise = Promise.reject(new Error("Error!"));
  rejectedPromise.catch(console.log); // Error: Error!

  // 위의 코드와 동일하게 동작
  const rejectedPromise = new Promise((_, reject) => reject(new Error("Error!")));
  rejectedPromise.catch(console.log); // Error: Error!
  ```

<br/>

### (2) **`Promise.all`**

- 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용

```jsx
const requestData1 = () =>
  // 첫 번째 프로미스 : 3초 후에 1을 resolve
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  // 두 번째 프로미스 : 2초 후에 2를 resolve
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  // 세 번째 프로미스 : 1초 후에 3을 resolve
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

// 세 개의 비동기 처리를 병렬로 처리
Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [1, 2, 3] ⇒ 약 3초 소요
  .catch(console.error);
```

- `Promise.all` 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다.
  - 전달받은 모든 프로미스가 모두 `fulfilled` 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스 반환한다.
- `Promise.all` 메서드는 인수로 전달받은 배열의 모든 프로미스가 모두 `fulfilled` 상태가 되면 종료한다.
  - `Promise.all` 메서드가 종료하는데 걸리는 시간은 가장 늦게 `fulfilled` 상태가 되는 프로미스의 처리 시간보다 조금 더 길다.
- **`Promise.all` 메서드는 처리 순서가 보장된다.**
  - 모든 프로미스가 `fulfilled` 상태가 되면 `resolve`된 처리 결과를 모두 배열에 저장해 새로운 프로미스를 반환한다.
  - 이때 첫 번째 프로미스가 가장 나중에 `fulfilled` 상태가 되어도 `Promise.all` 메서드는 첫 번째 프로미스가 `resolve`한 처리 결과부터 차례대로 배열에 저장해 그 배열을 resolve하는 새로운 프로미스를 반환하므로 **처리 순서가 보장**된다.
- `Promise.all` 메서드는 인수로 전달받은 배열의 프로미스가 하나라도 `reject` 상태가 되면 나머지 프로미스가 `fulfilled` 상태가 되는 것을 기다리지 않고 즉시 종료한다.
  ```jsx
  Promise.all([
    new Promise((_, reject) => setTimeout(() => reject(new Error("Error 1")), 3000)),
    new Promise((_, reject) => setTimeout(() => reject(new Error("Error 2")), 2000)),
    new Promise((_, reject) => setTimeout(() => reject(new Error("Error 3")), 1000)),
  ])
    .then(console.log)
    .catch(console.error); // Error: Error 3
  ```
  - 가장 먼저 `reject` 상태가 된 프로미스의 에러가 `catch` 메서드로 전달된다.
  - 인수로 전달받은 이터러블의 요소가 프로미스가 아닌 경우에는 `Promise.resolve` 메서드를 통해 프로미스로 래핑한다.
    ```jsx
    Promise.all([
      1, // Promise.resolve(1)
      2, // Promise.resolve(2)
      3, // Promise.resolve(3)
    ])
      .then(console.log) // [1, 2, 3]
      .catch(console.error);
    ```

<br/>

### (3) **`Promise.race`**

- **`Promise.race` 메서드는** 프로미스를 요소로 갖는 배열 들의 이터러블을 인수로 전달받아서 **가장 먼저 `fulfilled` 상태가 된 프로미스 처리 결과를 `resolve`하는 새로운 프로미스 반환**
  - `Promise.all` 메서드처럼 모든 프로미스가 `fulfilled` 상태가 되는 것을 기다리는 것이 ❌
- 인수로 전달받은 배열의 프로미스가 하나라도 `reject` 상태가 되면 에러를 `reject`하는 새로운 프로미스를 즉시 반환 ⇒ `Promise.all` 메서드와 동일하게 처리

```jsx
Promise.race([
  new Promise((resolve) => setTimeout(() => resolve(1), 3000)),
  new Promise((resolve) => setTimeout(() => resolve(2), 2000)),
  new Promise((resolve) => setTimeout(() => resolve(3), 1000)),
])
  .then(console.log) // 3
  .catch(console.error);
```

<br/>

### (4) **`Promise.allSettled`**

- ES11(ECMAScript 2020)에 도입
- `Promise.allSettled` 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받고, 전달받은 프로미스가 모두 `settled` 상태가 되면 처리 결과를 배열로 반환한다.
- `Promise.allSettled` 메서드가 반환한 배열에는 `fulfilled` 또는 `rejected` 상태와는 상관 없이, 인수로 전달 받은 모든 프로미스들의 처리 결과가 모두 담겨져 있다.
  - 프로미스의 처리 결과를 나타내는 객체
    - 프로미스가 `fulfilled` 상태인 경우 ⇒ 비동기 처리 상태를 나타내는 `status` 프로퍼티와 처리 결과를 나타내는 `value` 프로퍼티를 가짐
    - 프로미스가 `rejected` 상태인 경우 ⇒ 비동기 처리 상태를 나타내는 `status` 프로퍼티와 에러를 나타내는 `reason` 프로퍼티를 가짐
  ```jsx
  Promise.allSettled([
    new Promise((resolve) => setTimeout(() => resolve(1), 2000)),
    new Promise((_, reject) => setTimeout(() => reject(new Error("Error!")), 1000)),
  ]).then(console.log);
  /*
  [
    0: {status: 'fulfilled', value: 1}
    1: {status: 'rejected', reason: Error: Error! at <anonymous>:3:54}
  ]
  */
  ```

<br/><br/>

## 7) 마이크로태스크 큐(**microtask queue/job queue**)

- **마이크로태스크 큐는 태스크 큐와는 별도의 큐로, 프로미스의 후속 처리 메서드의 콜백 함수가 일시 저장되는 영역**
  - 그 외의 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 일시 저장된다.
- **마이크로태스크 큐는 태스크 큐보다 우선순위가 높다.**
  - 이벤트 루프는 콜 스백이 비면, 먼저 마이크로태스크 큐에서 대기하고 있는 함수를 가져와 실행한다.
  - 이후 마이크로태스크 큐가 비면 태스크 큐에서 대기하고 있는 함수를 가져와 실행한다.

```jsx
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));

// 출력 순서 : 2 ➝ 3 ➝ 1 (프로미스 후속처리 메서드의 콜백 함수 실행이 우선순위가 더 높음)
```

<br/><br/>

## 8) `fetch`

- HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API
- `fetch` 함수에는 HTTP 요청을 전송할 URL, HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.
  - `fetch` 함수에 첫 번째 인수로 URL만 전달하면 `GET` 요청을 전송함
  ```jsx
  const promise = fetch(url [, options])
  ```
- **`fetch` 함수는 HTTP 응답을 나타내는 `Response` 객체를 래핑한 `Promise` 객체를 반환**
  - 따라서, 후속 처리 메서드 `then`을 통해 프로미스가 `resolve`한 `Response` 객체를 전달 받을 수 있다.
  - `Response` 객체는 HTTP 응답을 나타내는 다양한 메서드 제공한다.
- `fetch` 함수를 사용할 때는 에러 처리에 주의해야 한다.
  - `fetch` 함수가 반환하는 프로미스는 기본적으로 **404 Not Found** 또는 **500 Internal Server Error** 와 같은 HTTP 에러가 발생하더라도 에러를 `reject` 하지 않고 불리언 타입의 `ok` 상태를 `false`로 설정한 `Response` 객체를 `resolve` 한다.
  - 오프라인 등 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 `reject` 한다.
  - 따라서, `fetch` 함수가 반환한 프로미스가 `resolve`한 불리언 타입의 `ok` 상태를 확인하여 명시적으로 에러를 처리할 필요가 있다.
  - cf) `axios`는 모든 HTTP 에러를 `reject` 하는 프로미스를 반환 ⇒ 모든 에러를 `catch`에서 처리할 수 있고 인터셉터, 요청 설정 등 다양한 기능을 제공하므로 `fetch`보다 편리하다.
- [fetch함수에 대한 자세한 내용은 MDN 페이지에서 확인](https://developer.mozilla.org/ko/docs/Web/API/Fetch_API/Using_Fetch)
