# 📒47장_ 에러 처리
### 📑목차
- [try … catch … finally 문](#try--catch--finally-문)
- [Error 객체](#error-객체)
- [throw 문](#throw-문)
- [에러의 전파](#에러의-전파)

### ⚡Quick Summary
- `try … catch … finally` 문: finally 문 생략 가능
- `new Error([message])`로 에러 객체 생성 & `Error.message`, `Error.stack` 프로퍼티를 가짐
- `try` 문에서 `throw` 문으로 에러(보통 에러 객체지만 어떤 표현식이든 가능)를 발생시키면 `catch` 문이 실행됨
- 에러는 **호출자(caller) 방향, 콜 스택의 아래 방향**으로 전파됨
    - 원하는 위치에서 에러 캐치 가능
    - 태스크 큐나 마이크로태스크 큐에 일시 저장되었다가 콜 스택이 비면 실행되는 비동기 함수 setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수는 에러를 전파할 호출자가 존재하지 않음

## 📌try … catch … finally 문
- `finally` 문은 생략 가능
```js
console.log('[Start]');

try {
  // 실행할 코드(에러가 발생할 가능성이 있는 코드)
  foo();
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행된다.
  // err에는 try 코드 블록에서 발생한 Error 객체가 전달된다.
  console.error(err); // ReferenceError: foo is not defined
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행된다.
  console.log('finally');
}

// try...catch...finally 문으로 에러를 처리하면 프로그램이 강제 종료되지 않는다.
console.log('[End]');
```

## 📌Error 객체
```js
new Error([message]);
```
- `Error` 생성자 함수로 에러 객체 생성 가능
- 에러 메시지를 인수로 전달 가능
- ✔️에러 객체 프로퍼티
    |프로퍼티|설명
    |--|--|
    |`message`|Error 생성자 함수에 인수로 전달한 에러 메시지|
    |`stack`|에러를 발생시킨 콜 스택의 호출 정보를 나타내는 문자열 (디버깅 목적)|
- 자바스크립트는 Error 생성자 함수를 포함해 7가지의 에러 객체를 생성할 수 있는 Error 생성자 함수를 제공
    |생성자 함수|인스턴스|
    |--|--|
    |Error|일반적 에러 객체|
    |SyntaxError|자바스크립트 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체|
    |ReferenceError|참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체|
    |TypeError|피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체|
    |RangeError|숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체|
    |URIError|encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체|
    |EvalError|eval 함수에서 발생하는 에러 객체|

    ```js
    1 @ 1;    // SyntaxError: Invalid or unexpected token
    foo();    // ReferenceError: foo is not defined
    null.foo; // TypeError: Cannot read property 'foo' of null
    new Array(-1); // RangeError: Invalid array length
    decodeURIComponent('%'); // URIError: URI malformed
    ```

## 📌throw 문
- 에러 객체 생성과 에러 발생은 별개!
- ✔️에러를 발생시키려면 `try` 코드 블록에서 `throw` 문으로 에러 객체를 던져야 함
    ```js
    throw expression;
    ```
    - 표현식은 어떤 값이라도 상관없지만 일반적으로 에러 객체를 지정
    - `catch` 코드 블록에 에러 변수가 생성되고 던져진 에러 객체가 할당되어 `catch` 코드 블록이 실행됨!

## 📌에러의 전파
- ⭐에러는 **호출자(caller) 방향, 콜 스택의 아래 방향**으로 전파됨!
- throw된 에러를 캐치하지 않으면 프로그램이 강제 종료돔
- ⚠️비동기 함수인 setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수는 호출자가 없음
    - setTimeout의 콜백 함수: 태스크 큐
    - 프로미스 후속 처리 메서드: 마이크로태스크 큐
    - 콜 스택이 비어야 이벤트 루프에 의해 콜 스택으로 푸시되어 실행되기 때문에 에러를 전파할 호출자가 존재 ❌
```js
const foo = () => {
  throw Error('foo에서 발생한 에러'); // ④
};

const bar = () => {
  foo(); // ③
};

const baz = () => {
  bar(); // ②
};

try {
  baz(); // ①
} catch (err) {
  console.error(err);
}
```
![image](https://github.com/namu56/modern-javascript-study/assets/71831926/8f34fb3b-757b-467a-859e-d55d8f401a6e)