## 프로미스

- 자바스크립트의 비동기 처리를 위한 하나의 패턴으로 콜백 함수를 사용하였지만,<br>
콜백 헬로 인한 가독성 문제와 비동기 처리 중 발생한 에러의 처리가 곤란하여 여러 개의 비동기 처리에 한계가 있었다.

- ES6에서는 프로미스 패턴은 기존의 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이 있다.


### 콜백 헬

> 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출하는 상황이 중첩되어 복잡도가 높아지는 현상

```jsx
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콘솔에 출력한다.
      console.log(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 post를 취득
get('https://jsonplaceholder.typicode.com/posts/1');
/*
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere ...",
  "body": "quia et suscipit ..."
}
*/
```

- get은 비동기 함수이다. 비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료된다.
- 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다. > 기대한 대로 동작하지 않는다.

🎈 비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없다.<br>
따라서 비동기 함수의 처리결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다.


### 에러 처리의 한계

```jsx
try {
  setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error('캐치한 에러', e);

}
```

에러를 캐치하지 못하는 이유는 비동기 함수인 setTimeout은 비동기 함수이므로 콜백 함수가 호출되는 것을 기다리지 않고 즉시 종료되어 콜 스택에서 제거된다.   
이후 타이머가 만료되면 setTimeout 함수의 콜백 함수는 태스크 큐로 푸시되고 콜 스택이 비어졌을 때 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.   
    
setTimeout 함수의 콜백 함수가 실행될 때 setTime 함수는 이미 콜 스택에서 제거된 상태다    
이것은 setTimeout 함수의 콜백 함수를 호출한 것이 setTimeout 함수가 아니라는 것을 의미한다.   
setTimeout 함수의 콜백 함수의 호출자가 setTimeout 함수라면 콜 스택의 현재 실행중인 실행 컨텍스트가 콜백 함수의 실행 컨텍스트일 때 현재 실행 중인 실행 컨텍스트의 하위 실행 컨텍스트가    
setTimeout 함수여야 한다.   
   
에러는 호출자 방향으로 전파된다.   
즉, 콜 스택의 아래 방향으로 전파된다.   
하지만 앞에서 살펴본 바와 같이 setTimeout 함수의 콜백 함수를 호출하는 것은 setTimeout 함수가 아니다.   따라서 setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.   

#### try ... catch ... finally 문

> 에러처리를 구현하는 방법으로 try 코드 블록이 먼저 실행된다. 이후 try 코드 블록에 포함된 문 중에서 에러가 발생할 경우 <br>
해당 에러는 catch 문의 err 변수로 전달되고 catch 문이 실행된다. finally는 에러 발생과 상관없이 반드시 한번 실행된다.

### 프로미스의 생성

- Promise 생성자 함수를 new 연산자와 함께 호출하면 프로미스 객체를 생성한다.

```jsx
const promise = new Promise((resolve, reject) => {
    if (true) {
        resolve('성공');
    } else {
        reject('실패');
    }
});
```

#### 프로미스의 비동기 처리 상태 정보

|프로미스의 상태 정보| 의미 | 상태 변경 조건 |
|:--:|:--:|:--:|
| pending | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled | 비동기 처리가 수행된 상태(성공) | resolve 함수 호출 |
| rejected | 비동기 처리가 수행된 상태(실패) | reject 함수 호출 |

### 프로미스의 후속 처리 메서드 

### 1) Promise.prototype.then   
then 메서드는 두 개의 콜백 함수를 인수로 전달받는다.   
- 첫 번째 콜백 함수는 프로미스가 fullfilled 상태(resolve 함수가 호출된 상태)가 되면 호출된다. 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.   
- 두 번재 콜백 함수는 프로미스가 rejected 상태(reject 함수가 호출된 상태)가 되면 호출된다. 이때 콜백 함수는 프로미스의 에러를 인수로 전달받는다.   

   
### 2) Promise.prototype.catch   
catch 메서드는 한 개의 콜백 함수를 인수로 전달받는다.   
catch 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우만 호출된다.   
   
### 3) Promise.prototype.finally
finally 메서드는 한 개의 콜백 함수를 인수로 전달받는다.   
finally 메서드의 콜백 함수는 프로미스의 성공(fulfilled) 또는 실패(rejected)와 상관없이 무조건 한 번 호출된다.   
finally 메서드는 프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용하다.  finally 메서드도 then/catch 메서드와 마찬가지로 언제나 프로미스를 반환한다.   

### 프로미스의 에러 처리   

- 프로미스는 콜백 패턴과 다르게 에러를 문제없이 처리할 수 있다.    
- 비동기 처리에서 발생한 에러는 then 메서드의 두 번째 콜백 함수로 처리할 수 있다.
 
```jsx
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl).then(
  res => console.log(res),
  err => console.error(err)
); // Error: 404
```

- 비동기 처리에서 발생한 에러는 프로미스의 후속 처리 메서드 catch를 사용해 처리할 수도 있다.

```jsx
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then(res => console.log(res))
  .catch(err => console.error(err)); // Error: 404
```

### 프로미스 체이닝    

- 비동기 처리를 위한 콜백 패턴은 콜백 헬이 발생하는 문제가 있지만 프로미스는 then, catch, finally 후속 처리 메서드를 통해 콜백 헬을 해결한다.   

```jsx
const url = 'https://jsonplaceholder.typicode.com';

// id가 1인 post의 userId를 취득
promiseGet(`${url}/posts/1`)
  // 취득한 post의 userId로 user 정보를 취득
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then(userInfo => console.log(userInfo))
  .catch(err => console.error(err));
```

위 예제에서 then -> then -> catch 순서로 후속 처리 메서드를 호출했다.   
then, catch, finally 후속 처리 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있다.   
이를 프로미스 체이닝이라 한다.   
